"""Sample RFQs, drawings and gold specs (generated by scripts/gen_drawings.py)."""

from __future__ import annotations

import json
import re

import pymupdf
import pytest

from rfq_agent.config import SAMPLES_DIR
from rfq_agent.data.repositories import CatalogRepo, MaterialRepo
from rfq_agent.models import DrawingSpec, FeatureType, RFQRequest, ShapeClass

RFQS = {
    "RFQ-2026-0101": "SH-4711",
    "RFQ-2026-0102": "FL-2208",
    "RFQ-2026-0103": "BR-0930",
    "RFQ-2026-0104": "ASM-5100",
}
TUNING = [(SAMPLES_DIR / r, pn) for r, pn in RFQS.items()] + [(SAMPLES_DIR / "eval_only", "GR-3340")]
HOLDOUT = [(SAMPLES_DIR / "holdout", pn) for pn in ("BS-60218", "CP-7390", "PS-2045")]
DRAWINGS = TUNING + HOLDOUT


def load_spec(pn: str) -> DrawingSpec:
    d = next(d for d, p in DRAWINGS if p == pn)
    return DrawingSpec.model_validate_json((d / "expected" / f"{pn}.json").read_text(encoding="utf-8"))


def page_text(pdf) -> str:
    with pymupdf.open(pdf) as doc:
        return re.sub(r"\s+", " ", doc[0].get_text())


@pytest.mark.parametrize(("d", "pn"), DRAWINGS)
def test_drawing_files_and_render(d, pn):
    pdf, png = d / "drawings" / f"{pn}.pdf", d / "drawings" / f"{pn}.png"
    assert pdf.exists() and png.exists()
    with pymupdf.open(pdf) as doc:
        assert doc.page_count == 1
        w, h = doc[0].rect.width * 25.4 / 72, doc[0].rect.height * 25.4 / 72
        assert abs(w - 420) < 1 and abs(h - 297) < 1  # A3 landscape
        pix = doc[0].get_pixmap(dpi=50)
        assert pix.width > pix.height > 100
    spec = load_spec(pn)
    assert spec.drawing_file == f"{pn}.pdf"
    assert spec.title_block.part_number == pn


@pytest.mark.parametrize(("d", "pn"), DRAWINGS)
def test_evidence_printed_on_drawing(d, pn):
    """Gold evidence must be verbatim text of the PDF (single-source guarantee)."""
    text = page_text(d / "drawings" / f"{pn}.pdf")
    spec = load_spec(pn)
    for f in spec.features:
        assert f.evidence and f.evidence.text in text, (f.id, f.evidence)
    for field, ev in spec.title_block.evidence.items():
        assert ev.text in text, field
    for n in spec.notes:
        assert n in text
    for it in spec.parts_list:
        assert it.description in text
    for t in (spec.heat_treatment, spec.surface_treatment):
        if t:
            assert t in text


@pytest.mark.parametrize("rfq", list(RFQS))
def test_rfq_gold_matches_email(rfq):
    d = SAMPLES_DIR / rfq
    email = (d / "email.txt").read_text(encoding="utf-8")
    req = RFQRequest.model_validate_json((d / "expected" / "rfq.json").read_text(encoding="utf-8"))
    assert req.rfq_id == rfq
    assert email.startswith("From: ") and "\nSubject: " in email and "\nDate: " in email
    assert req.contact_email in email and req.customer_name in email
    for it in req.items:
        assert it.drawing_ref in email
        assert (d / "drawings" / it.drawing_ref).exists()
        assert it.quantities and it.requested_delivery and it.requested_delivery.year == 2026
        assert it.requested_delivery.month in (11, 12)


def test_rfq_languages_and_quantities():
    gold = {
        r: json.loads((SAMPLES_DIR / r / "expected" / "rfq.json").read_text(encoding="utf-8")) for r in RFQS
    }
    assert [gold[r]["language"] for r in RFQS] == ["de", "en", "en", "de"]
    assert [gold[r]["items"][0]["quantities"] for r in RFQS] == [[200, 500], [1000], [300], [50]]
    assert "EN 10204 3.1 certificate" in gold["RFQ-2026-0101"]["special_requirements"]


def test_shaft_triggers_precision_rules(db):
    s = load_spec("SH-4711")
    assert s.heat_treatment and "QT" in s.heat_treatment
    fits = [f.tolerance.fit for f in s.features if f.tolerance]
    assert fits.count("k6") == 2
    assert any(f.ra_um == 0.8 for f in s.features)
    assert {FeatureType.KEYWAY, FeatureType.THREAD} <= {f.type for f in s.features}
    assert MaterialRepo(db).resolve(s.title_block.material) == "42CrMo4"


def test_flange(db):
    s = load_spec("FL-2208")
    assert s.surface_treatment == "anodized black"
    assert any(f.tolerance and f.tolerance.fit == "H7" and f.nominal_mm == 80 for f in s.features)
    assert MaterialRepo(db).resolve(s.title_block.material) == "AW6082"


def test_bracket_triggers_val001_dfm001_dfm002():
    s = load_spec("BR-0930")
    assert s.title_block.material is None and "material" not in s.title_block.evidence
    assert s.envelope.shape_class == ShapeClass.PRISMATIC
    walls = [f for f in s.features if f.type == FeatureType.WALL]
    assert walls and walls[0].nominal_mm < 2
    holes = [f for f in s.features if f.type == FeatureType.HOLE and f.length_mm / f.nominal_mm > 10]
    assert holes and holes[0].nominal_mm == 6 and holes[0].length_mm == 80


def test_assembly_parts_list_matches_catalog(db):
    s = load_spec("ASM-5100")
    assert s.envelope.shape_class == ShapeClass.ASSEMBLY
    assert len(s.parts_list) == 7
    by_pn = {it.part_number: it for it in s.parts_list if it.part_number}
    assert {"HS-5101", "SH-5102", "EC-5103"} <= set(by_pn)
    cat = CatalogRepo(db)
    matched = {}
    for it in s.parts_list:
        m = cat.match(it.part_number, it.description, it.standard)
        matched[it.item_no] = m[0]["part_number"] if m else None
    assert matched == {
        1: None,
        2: None,
        3: "6204-2RS",
        4: "SEAL-20x35x7",
        5: "ISO4762-M5x16",
        6: None,
        7: "DIN471-20",
    }
    assert by_pn["6204-2RS"].quantity == 2
    assert next(it for it in s.parts_list if it.item_no == 5).quantity == 4


def test_gear_eval():
    s = load_spec("GR-3340")
    g = next(f for f in s.features if f.type == FeatureType.GEAR_TEETH)
    assert (g.gear_module, g.gear_teeth, g.face_width_mm) == (2, 40, 20)
    assert s.heat_treatment == "case hardened 58-62 HRC"
    assert s.title_block.material == "16MnCr5"


def test_generator_layout_clean():
    """Regenerating produces no overlapping labels (legibility) and identical gold JSON."""
    import gen_drawings

    for p in [gen_drawings.shaft(), gen_drawings.flange(), gen_drawings.bracket(), gen_drawings.assembly()]:
        s = gen_drawings.Sheet()
        gen_drawings.frame(s)
        gen_drawings.title_block(s, p)
        p.draw(s, p)
        assert s.text_overlaps() == [], p.pn
        gen_drawings.plt.close(s.fig)
        assert p.spec() == load_spec(p.pn)
    assert gen_drawings.gear().spec() == load_spec("GR-3340")


def test_holdout_generator_and_gold():
    """Hold-out parts: clean layout, gold JSON == generator definition, same sheet zones as the tuning set."""
    import gen_drawings

    parts = gen_drawings.holdout_parts()
    assert [p.pn for p in parts] == [pn for _, pn in HOLDOUT]
    for p in parts:
        assert p.layout == "alt"
        s = gen_drawings.draw_sheet(p)
        assert s.text_overlaps() == [], p.pn
        # every text label of the views stays left of the right column (the zone drawing.py crops as views)
        for txt in s.ax.texts:
            x, _ = txt.get_position()
            if x < gen_drawings.RIGHT_X0:
                r = s.fig.canvas.get_renderer()
                bb = txt.get_window_extent(r).transformed(s.ax.transData.inverted())
                assert bb.x1 < gen_drawings.RIGHT_X0, (p.pn, txt.get_text())
        gen_drawings.plt.close(s.fig)
        assert p.spec() == load_spec(p.pn)


def test_holdout_differs_from_tuning_set():
    """No hold-out part number, material or feature callout is reused from the tuning set."""
    tuning = [load_spec(pn) for _, pn in TUNING]
    holdout = [load_spec(pn) for _, pn in HOLDOUT]
    t_ev = {f.evidence.text for s in tuning for f in s.features}
    t_mat = {s.title_block.material for s in tuning}
    for s in holdout:
        assert s.title_block.material not in t_mat
        assert not {f.evidence.text for f in s.features} & t_ev, s.drawing_file


def test_holdout_gold_is_consistent(db):
    mats = MaterialRepo(db)
    expected_codes = {"BS-60218": "X5CrNi18-10", "CP-7390": "GJS500", "PS-2045": "C45"}
    for _, pn in HOLDOUT:
        s = load_spec(pn)
        assert mats.resolve(s.title_block.material) == expected_codes[pn]
        assert [f.id for f in s.features] == [f"F{i}" for i in range(1, len(s.features) + 1)]
        e = s.envelope
        for f in s.features:
            assert f.nominal_mm and f.nominal_mm > 0, (pn, f.id)
            if e.shape_class == ShapeClass.ROTATIONAL and f.type == FeatureType.OUTER_DIAMETER:
                assert f.nominal_mm <= e.max_diameter_mm
    bushing, plate, pinion = (load_spec(pn) for _, pn in HOLDOUT)
    assert bushing.title_block.scale == "2:1" and bushing.surface_treatment == "passivated"
    assert plate.envelope.shape_class == ShapeClass.PRISMATIC
    assert {f.type for f in plate.features} >= {FeatureType.SLOT, FeatureType.THREAD, FeatureType.BORE}
    g = next(f for f in pinion.features if f.type == FeatureType.GEAR_TEETH)
    assert (g.gear_module, g.gear_teeth, g.nominal_mm) == (2.5, 17, 42.5)
    assert any(f.type == FeatureType.SPLINE for f in pinion.features)
